version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true

search:
   :ranking:
     index.html: 10

     # Documentation files primarily for contributors are less important than code files.
     contribute.html: -2
     CODE_OF_CONDUCT.html: -3
     SECURITY.html: -3
     CONTRIBUTING.html: -3

     # Files that the user does not need
     404.html: -8
     pre.html: -10
     post.html: -10

   ignore:
     # Custom files to ignore
     - pre.html
     - post.html

     # Defaults
     - search.html
     - search/index.html
     - 404.html
     - 404/index.html
