version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs


build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true



search:
   ranking:
     index.html: 6

     # Documentation files primarily for contributors are less important than code files.
     contribute.html: -2
     CODE_OF_CONDUCT.html: -3
     SECURITY.html: -3
     CONTRIBUTING.html: -3

   ignore:
     - pre.html
     - post.html
     - 404.html